# FROM <image>:<tag>
# RUN ["<커맨드>", "<파라미터1>", "<파라미터2>"]
# WORKDIR <이동할 경로>
# ENV <키> <값>
# ENV <키>=<값>
# COPY <src>... <dest>
# COPY ["<src>",... "<dest>"]
# ARG <이름>
# ARG <이름>=<기본 값>
# ENTRYPOINT ["<커맨드>", "<파라미터1>", "<파라미터2>"]
# ENTRYPOINT <전체 커맨드>
# CMD ["<커맨드>","<파라미터1>","<파라미터2>"] CMD ["<파라미터1>","<파라미터2>"] CMD <전체 커맨드>

# FROM base image를 설정
# RUN image build시 커맨드 실행
# WORKDIR 작업 디렉토리 설정
# ENV 환경 변수 설정
# COPY/ADD image의 filesystem으로 파일 또는 디렉토리 복사
# ARG build 시 넘어 올수 있는 인자 설정
# ENTRYPOINT image 실행 시 항상 실행되야 하는 커맨드 설정
# CMD image 실행 시 디폴트 커맨드 또는 파라미터 설정


FROM oraclelinux:9

LABEL maintainer = "withgossing@gmail.com"

RUN yum -y update
RUN yum -y install python3-pip filewalld net-tools mariadb-server
RUN pip install jupyterlab
RUN pip install flask

# jupyter lab --ip=0.0.0.0 --allow-root --no-browser


# FROM mariadb 
# ENV MYSQL_ROOT_PASSWORD Abc33151@@ 
# ENV MYSQL_DATABASE mydb 
# COPY ./maria /var/lib/mysql 
# EXPOSE 3310 
# ENTRYPOINT ["mysqld", "--user=root"]